-- MySQL Script generated by MySQL Workbench
-- 11/26/18 16:27:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`Consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Consultorio` (
  `id_consultorio` INT NOT NULL,
  `edificio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_consultorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`especialidad` (
  `id_especi` INT NOT NULL,
  `nombre_especialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_especi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`recursos_hum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`recursos_hum` (
  `id_personal` INT NOT NULL,
  `nombre_per` VARCHAR(45) NULL,
  `telefono` BIGINT(10) NULL,
  `puesto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`horarios` (
  `id_horario` INT NOT NULL,
  `tipo_horario` VARCHAR(45) NULL,
  `time` TIME(5) NULL,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`medico` (
  `id_medico` INT NOT NULL,
  `telefono` BIGINT(10) NULL,
  `correo` VARCHAR(45) NULL,
  `especialidad_id_especi` INT NOT NULL,
  `recursos_hum_id_personal` INT NOT NULL,
  `nombre_medico` VARCHAR(45) NULL,
  `horarios_id_horario` INT NOT NULL,
  PRIMARY KEY (`id_medico`),
  INDEX `fk_medico_especialidad_idx` (`especialidad_id_especi` ASC),
  INDEX `fk_medico_recursos_hum1_idx` (`recursos_hum_id_personal` ASC),
  INDEX `fk_medico_horarios1_idx` (`horarios_id_horario` ASC),
  CONSTRAINT `fk_medico_especialidad`
    FOREIGN KEY (`especialidad_id_especi`)
    REFERENCES `hospital`.`especialidad` (`id_especi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medico_recursos_hum1`
    FOREIGN KEY (`recursos_hum_id_personal`)
    REFERENCES `hospital`.`recursos_hum` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medico_horarios1`
    FOREIGN KEY (`horarios_id_horario`)
    REFERENCES `hospital`.`horarios` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`paciente` (
  `id_paciente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `edad` INT NULL,
  `tipo_sangre` VARCHAR(45) NULL,
  `motivo_ingre` VARCHAR(45) NULL,
  `sintomas` VARCHAR(45) NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Consulta` (
  `id_consulta` INT NOT NULL,
  `fecha` DATE NULL,
  `hora` TIME(5) NULL,
  `Consultorio_id_consultorio` INT NOT NULL,
  `medico_id_medico` INT NOT NULL,
  `paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_consulta`),
  INDEX `fk_Consulta_Consultorio1_idx` (`Consultorio_id_consultorio` ASC),
  INDEX `fk_Consulta_medico1_idx` (`medico_id_medico` ASC),
  INDEX `fk_Consulta_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_Consulta_Consultorio1`
    FOREIGN KEY (`Consultorio_id_consultorio`)
    REFERENCES `hospital`.`Consultorio` (`id_consultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_medico1`
    FOREIGN KEY (`medico_id_medico`)
    REFERENCES `hospital`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`proveedor` (
  `id_proveedor` INT NOT NULL,
  `nombre_proveedor` VARCHAR(45) NULL,
  `telefono_provee` BIGINT(10) NULL,
  `productos` VARCHAR(50) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`marca` (
  `id_marca` INT NOT NULL,
  `nombre_marca` VARCHAR(45) NULL,
  `empresa` VARCHAR(45) NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`laboratorio_medi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`laboratorio_medi` (
  `id_labo` INT NOT NULL,
  `nombre_laboratorio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_labo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`medicamento` (
  `id_medicamento` INT NOT NULL,
  `nombre_medi` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `proveedor_id_proveedor` INT NOT NULL,
  `marca_id_marca` INT NOT NULL,
  `laboratorio_medi_id_labo` INT NOT NULL,
  PRIMARY KEY (`id_medicamento`),
  INDEX `fk_medicamento_proveedor1_idx` (`proveedor_id_proveedor` ASC),
  INDEX `fk_medicamento_marca1_idx` (`marca_id_marca` ASC),
  INDEX `fk_medicamento_laboratorio_medi1_idx` (`laboratorio_medi_id_labo` ASC),
  CONSTRAINT `fk_medicamento_proveedor1`
    FOREIGN KEY (`proveedor_id_proveedor`)
    REFERENCES `hospital`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_marca1`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `hospital`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_laboratorio_medi1`
    FOREIGN KEY (`laboratorio_medi_id_labo`)
    REFERENCES `hospital`.`laboratorio_medi` (`id_labo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`detalle_com`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`detalle_com` (
  `id_compra` INT NOT NULL,
  `cantidad` INT NULL,
  `nombre_medicamento` VARCHAR(45) NULL,
  `total` FLOAT NULL,
  `medicamento_id_medicamento` INT NOT NULL,
  `laboratorio_medi_id_labo` INT NOT NULL,
  `num_lote` INT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_detalle_com_medicamento1_idx` (`medicamento_id_medicamento` ASC),
  INDEX `fk_detalle_com_laboratorio_medi1_idx` (`laboratorio_medi_id_labo` ASC),
  CONSTRAINT `fk_detalle_com_medicamento1`
    FOREIGN KEY (`medicamento_id_medicamento`)
    REFERENCES `hospital`.`medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_com_laboratorio_medi1`
    FOREIGN KEY (`laboratorio_medi_id_labo`)
    REFERENCES `hospital`.`laboratorio_medi` (`id_labo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Compra_medi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Compra_medi` (
  `id_compra` INT NOT NULL,
  `total` DOUBLE NULL,
  `detalle_com_id_compra` INT NOT NULL,
  `fecha_caducidad` DATE NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_Compra_medi_detalle_com1_idx` (`detalle_com_id_compra` ASC),
  CONSTRAINT `fk_Compra_medi_detalle_com1`
    FOREIGN KEY (`detalle_com_id_compra`)
    REFERENCES `hospital`.`detalle_com` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`tipos_labo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`tipos_labo` (
  `id_tipodelab` INT NOT NULL,
  `tipo_examen` VARCHAR(45) NULL,
  `descripción_examen` TEXT NULL,
  PRIMARY KEY (`id_tipodelab`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`examenes_labora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`examenes_labora` (
  `id_laboratorio` INT NOT NULL,
  `fecha_examen` DATE NULL,
  `hora_examen` TIME(5) NULL,
  `paciente_id_paciente` INT NOT NULL,
  `nombre_laboratorio` VARCHAR(45) NULL,
  `lugar_labor` VARCHAR(45) NULL,
  `nombre_examen` VARCHAR(45) NULL,
  `tipos_labo_id_tipodelab` INT NOT NULL,
  PRIMARY KEY (`id_laboratorio`),
  INDEX `fk_laboratorio_paciente1_idx` (`paciente_id_paciente` ASC),
  INDEX `fk_examenes_labora_tipos_labo1_idx` (`tipos_labo_id_tipodelab` ASC),
  CONSTRAINT `fk_laboratorio_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_examenes_labora_tipos_labo1`
    FOREIGN KEY (`tipos_labo_id_tipodelab`)
    REFERENCES `hospital`.`tipos_labo` (`id_tipodelab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`quirofano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`quirofano` (
  `id_quirofano` INT NOT NULL,
  `descrip_equipo` TEXT NULL,
  PRIMARY KEY (`id_quirofano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`enfermera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`enfermera` (
  `id_enfermera` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  `turno` VARCHAR(45) NULL,
  `telefono` BIGINT(10) NULL,
  `recursos_hum_id_personal` INT NOT NULL,
  `horarios_id_horario` INT NOT NULL,
  PRIMARY KEY (`id_enfermera`),
  INDEX `fk_enfermera_recursos_hum1_idx` (`recursos_hum_id_personal` ASC),
  INDEX `fk_enfermera_horarios1_idx` (`horarios_id_horario` ASC),
  CONSTRAINT `fk_enfermera_recursos_hum1`
    FOREIGN KEY (`recursos_hum_id_personal`)
    REFERENCES `hospital`.`recursos_hum` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enfermera_horarios1`
    FOREIGN KEY (`horarios_id_horario`)
    REFERENCES `hospital`.`horarios` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`egreso` (
  `id_egreso` INT NOT NULL,
  `fecha_ingreso` DATE NULL,
  `fecha_egreso` DATE NULL,
  `motivo_ingreso` VARCHAR(45) NULL,
  `motivo_egreso` VARCHAR(45) NULL,
  `tratamiento_aplicado` VARCHAR(45) NULL,
  `paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_egreso`),
  INDEX `fk_egreso_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_egreso_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`revision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`revision` (
  `signos vitales` TEXT NULL,
  `descri_eu` TEXT NULL,
  `fecha` DATE NULL,
  `hora` TIME(5) NULL,
  `paciente_id_paciente` INT NOT NULL,
  `enfermera_id_enfermera` INT NOT NULL,
  `egreso_id_egreso` INT NOT NULL,
  INDEX `fk_revision_paciente1_idx` (`paciente_id_paciente` ASC),
  INDEX `fk_revision_enfermera1_idx` (`enfermera_id_enfermera` ASC),
  INDEX `fk_revision_egreso1_idx` (`egreso_id_egreso` ASC),
  CONSTRAINT `fk_revision_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revision_enfermera1`
    FOREIGN KEY (`enfermera_id_enfermera`)
    REFERENCES `hospital`.`enfermera` (`id_enfermera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revision_egreso1`
    FOREIGN KEY (`egreso_id_egreso`)
    REFERENCES `hospital`.`egreso` (`id_egreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`receta` (
  `id_receta` INT NOT NULL,
  `medicamento_rece` VARCHAR(45) NULL,
  `Consulta_id_consulta` INT NOT NULL,
  `medico_id_medico` INT NOT NULL,
  PRIMARY KEY (`id_receta`),
  INDEX `fk_receta_Consulta1_idx` (`Consulta_id_consulta` ASC),
  INDEX `fk_receta_medico1_idx` (`medico_id_medico` ASC),
  CONSTRAINT `fk_receta_Consulta1`
    FOREIGN KEY (`Consulta_id_consulta`)
    REFERENCES `hospital`.`Consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receta_medico1`
    FOREIGN KEY (`medico_id_medico`)
    REFERENCES `hospital`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`forma_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`forma_pago` (
  `id_forma` INT NOT NULL,
  `forma_pago` VARCHAR(45) NULL,
  `seguro` VARCHAR(10) NULL,
  `Pago_de` VARCHAR(45) NULL,
  `paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_forma`),
  INDEX `fk_forma_pago_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_forma_pago_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`detalle_venta` (
  `id_venta` INT NOT NULL,
  `cantidad` INT NULL,
  `nombre_medi` VARCHAR(45) NULL,
  `total` FLOAT NULL,
  `medicamento_id_medicamento` INT NOT NULL,
  `laboratorio_medi_id_labo` INT NOT NULL,
  `num_lote` INT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_detalle_venta_medicamento1_idx` (`medicamento_id_medicamento` ASC),
  INDEX `fk_detalle_venta_laboratorio_medi1_idx` (`laboratorio_medi_id_labo` ASC),
  CONSTRAINT `fk_detalle_venta_medicamento1`
    FOREIGN KEY (`medicamento_id_medicamento`)
    REFERENCES `hospital`.`medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_laboratorio_medi1`
    FOREIGN KEY (`laboratorio_medi_id_labo`)
    REFERENCES `hospital`.`laboratorio_medi` (`id_labo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`farmacia` (
  `id_venta` INT NOT NULL,
  `total_final` FLOAT NULL,
  `fecha_compra` DATE NULL,
  `receta_id_receta` INT NOT NULL,
  `recursos_hum_id_personal` INT NOT NULL,
  `forma_pago_id_forma` INT NOT NULL,
  `detalle_venta_id_venta` INT NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_farmacia_receta1_idx` (`receta_id_receta` ASC),
  INDEX `fk_farmacia_recursos_hum1_idx` (`recursos_hum_id_personal` ASC),
  INDEX `fk_farmacia_forma_pago1_idx` (`forma_pago_id_forma` ASC),
  INDEX `fk_farmacia_detalle_venta1_idx` (`detalle_venta_id_venta` ASC),
  CONSTRAINT `fk_farmacia_receta1`
    FOREIGN KEY (`receta_id_receta`)
    REFERENCES `hospital`.`receta` (`id_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_farmacia_recursos_hum1`
    FOREIGN KEY (`recursos_hum_id_personal`)
    REFERENCES `hospital`.`recursos_hum` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_farmacia_forma_pago1`
    FOREIGN KEY (`forma_pago_id_forma`)
    REFERENCES `hospital`.`forma_pago` (`id_forma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_farmacia_detalle_venta1`
    FOREIGN KEY (`detalle_venta_id_venta`)
    REFERENCES `hospital`.`detalle_venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`banco_sangre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`banco_sangre` (
  `nombre_donador` VARCHAR(45) NOT NULL,
  `tipo_sangre` VARCHAR(45) NULL,
  `paciente_id_paciente` INT NOT NULL,
  INDEX `fk_banco_sangre_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_banco_sangre_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`camillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`camillero` (
  `id_camillero` INT NOT NULL,
  `nombre_camillero` VARCHAR(45) NULL,
  `horarios_id_horario` INT NOT NULL,
  PRIMARY KEY (`id_camillero`),
  INDEX `fk_camillero_horarios1_idx` (`horarios_id_horario` ASC),
  CONSTRAINT `fk_camillero_horarios1`
    FOREIGN KEY (`horarios_id_horario`)
    REFERENCES `hospital`.`horarios` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`anesteciologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`anesteciologo` (
  `id_aneste` INT NOT NULL,
  `nombre_aneste` VARCHAR(45) NULL,
  `recursos_hum_id_personal` INT NOT NULL,
  `horarios_id_horario` INT NOT NULL,
  PRIMARY KEY (`id_aneste`),
  INDEX `fk_anesteciologo_recursos_hum1_idx` (`recursos_hum_id_personal` ASC),
  INDEX `fk_anesteciologo_horarios1_idx` (`horarios_id_horario` ASC),
  CONSTRAINT `fk_anesteciologo_recursos_hum1`
    FOREIGN KEY (`recursos_hum_id_personal`)
    REFERENCES `hospital`.`recursos_hum` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anesteciologo_horarios1`
    FOREIGN KEY (`horarios_id_horario`)
    REFERENCES `hospital`.`horarios` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`nota_postoperatoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`nota_postoperatoria` (
  `id_post` INT NOT NULL,
  `diagnostico_preope` VARCHAR(45) NULL,
  `diagnostico_post` VARCHAR(45) NULL,
  `operacion_reali` VARCHAR(45) NULL,
  `paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_nota_postoperatoria_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_nota_postoperatoria_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`tipo_cirugia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`tipo_cirugia` (
  `id_tipociru` INT NOT NULL,
  `tipo_cirugia` VARCHAR(45) NULL,
  `descripcion_ciru` TEXT NULL,
  PRIMARY KEY (`id_tipociru`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`cirugia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`cirugia` (
  `id_cirugia` INT NOT NULL,
  `descripcion_cirugia` VARCHAR(45) NULL,
  `quirofano_id_quirofano` INT NOT NULL,
  `paciente_id_paciente` INT NOT NULL,
  `anesteciologo_id_aneste` INT NOT NULL,
  `nota_postoperatoria_id_post` INT NOT NULL,
  `tipo_cirugia_id_tipociru` INT NOT NULL,
  PRIMARY KEY (`id_cirugia`),
  INDEX `fk_cirugia_quirofano1_idx` (`quirofano_id_quirofano` ASC),
  INDEX `fk_cirugia_paciente1_idx` (`paciente_id_paciente` ASC),
  INDEX `fk_cirugia_anesteciologo1_idx` (`anesteciologo_id_aneste` ASC),
  INDEX `fk_cirugia_nota_postoperatoria1_idx` (`nota_postoperatoria_id_post` ASC),
  INDEX `fk_cirugia_tipo_cirugia1_idx` (`tipo_cirugia_id_tipociru` ASC),
  CONSTRAINT `fk_cirugia_quirofano1`
    FOREIGN KEY (`quirofano_id_quirofano`)
    REFERENCES `hospital`.`quirofano` (`id_quirofano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cirugia_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cirugia_anesteciologo1`
    FOREIGN KEY (`anesteciologo_id_aneste`)
    REFERENCES `hospital`.`anesteciologo` (`id_aneste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cirugia_nota_postoperatoria1`
    FOREIGN KEY (`nota_postoperatoria_id_post`)
    REFERENCES `hospital`.`nota_postoperatoria` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cirugia_tipo_cirugia1`
    FOREIGN KEY (`tipo_cirugia_id_tipociru`)
    REFERENCES `hospital`.`tipo_cirugia` (`id_tipociru`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`repor_cirugia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`repor_cirugia` (
  `id_reporte` INT NOT NULL,
  `enfermera_id_enfermera` INT NOT NULL,
  `camillero_id_camillero` INT NOT NULL,
  `cirugia_id_cirugia` INT NOT NULL,
  `medico_id_medico` INT NOT NULL,
  PRIMARY KEY (`id_reporte`),
  INDEX `fk_repor_cirugia_enfermera1_idx` (`enfermera_id_enfermera` ASC),
  INDEX `fk_repor_cirugia_camillero1_idx` (`camillero_id_camillero` ASC),
  INDEX `fk_repor_cirugia_cirugia1_idx` (`cirugia_id_cirugia` ASC),
  INDEX `fk_repor_cirugia_medico1_idx` (`medico_id_medico` ASC),
  CONSTRAINT `fk_repor_cirugia_enfermera1`
    FOREIGN KEY (`enfermera_id_enfermera`)
    REFERENCES `hospital`.`enfermera` (`id_enfermera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repor_cirugia_camillero1`
    FOREIGN KEY (`camillero_id_camillero`)
    REFERENCES `hospital`.`camillero` (`id_camillero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repor_cirugia_cirugia1`
    FOREIGN KEY (`cirugia_id_cirugia`)
    REFERENCES `hospital`.`cirugia` (`id_cirugia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repor_cirugia_medico1`
    FOREIGN KEY (`medico_id_medico`)
    REFERENCES `hospital`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`referenciaytraslado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`referenciaytraslado` (
  `id_traslado` INT NOT NULL,
  `estado_origen` VARCHAR(45) NULL,
  `estado_receptor` VARCHAR(45) NULL,
  `motivo_envio` VARCHAR(45) NULL,
  `paciente_id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_traslado`),
  INDEX `fk_referenciaytraslado_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_referenciaytraslado_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`urgencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`urgencias` (
  `id_urgencia` INT NOT NULL,
  `descripcion_urg` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `hora_ingreso` TIME(5) NULL,
  `medico_id_medico` INT NOT NULL,
  `paciente_id_paciente` INT NOT NULL,
  `enfermera_id_enfermera` INT NOT NULL,
  `referenciaytraslado_id_traslado` INT NOT NULL,
  `hora_salida` TIME(5) NULL,
  PRIMARY KEY (`id_urgencia`),
  INDEX `fk_urgencias_medico1_idx` (`medico_id_medico` ASC),
  INDEX `fk_urgencias_paciente1_idx` (`paciente_id_paciente` ASC),
  INDEX `fk_urgencias_enfermera1_idx` (`enfermera_id_enfermera` ASC),
  INDEX `fk_urgencias_referenciaytraslado1_idx` (`referenciaytraslado_id_traslado` ASC),
  CONSTRAINT `fk_urgencias_medico1`
    FOREIGN KEY (`medico_id_medico`)
    REFERENCES `hospital`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_urgencias_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_urgencias_enfermera1`
    FOREIGN KEY (`enfermera_id_enfermera`)
    REFERENCES `hospital`.`enfermera` (`id_enfermera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_urgencias_referenciaytraslado1`
    FOREIGN KEY (`referenciaytraslado_id_traslado`)
    REFERENCES `hospital`.`referenciaytraslado` (`id_traslado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`odontologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`odontologia` (
  `id_odon` INT NOT NULL,
  `odontograma` VARCHAR(45) NULL,
  `diagnostico` VARCHAR(45) NULL,
  `tratamiento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_odon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`antecedentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`antecedentes` (
  `id_antecedente` INT NOT NULL,
  `antecedentes_quirur` TEXT NULL,
  `fecha_ante_quirur` DATE NULL,
  `antecedentes_personales` TEXT NULL,
  `fecha_ante_personales` DATE NULL,
  PRIMARY KEY (`id_antecedente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`expediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`expediente` (
  `id_expe` INT NOT NULL,
  `padecimiento_actual` TEXT NULL,
  `habitus_exterior` TEXT NULL,
  `signosvitales` VARCHAR(45) NULL,
  `odontologia_id_odon` INT NULL,
  `paciente_id_paciente` INT NOT NULL,
  `fecha_actua` DATE NULL,
  `fecha_signos` DATE NULL,
  `hora_signos` TIME(5) NULL,
  `antecedentes_id_antecedente` INT NOT NULL,
  PRIMARY KEY (`id_expe`),
  INDEX `fk_expediente_odontologia1_idx` (`odontologia_id_odon` ASC),
  INDEX `fk_expediente_paciente1_idx` (`paciente_id_paciente` ASC),
  INDEX `fk_expediente_antecedentes1_idx` (`antecedentes_id_antecedente` ASC),
  CONSTRAINT `fk_expediente_odontologia1`
    FOREIGN KEY (`odontologia_id_odon`)
    REFERENCES `hospital`.`odontologia` (`id_odon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expediente_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expediente_antecedentes1`
    FOREIGN KEY (`antecedentes_id_antecedente`)
    REFERENCES `hospital`.`antecedentes` (`id_antecedente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`operaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`operaciones` (
  `id_operacion` INT NOT NULL,
  `tipo_operacion` VARCHAR(45) NULL,
  `monto` FLOAT NULL,
  `fecha` DATE NULL,
  `Compra_medi_id_compra` INT NOT NULL,
  `farmacia_id_venta` INT NOT NULL,
  PRIMARY KEY (`id_operacion`),
  INDEX `fk_operaciones_Compra_medi1_idx` (`Compra_medi_id_compra` ASC),
  INDEX `fk_operaciones_farmacia1_idx` (`farmacia_id_venta` ASC),
  CONSTRAINT `fk_operaciones_Compra_medi1`
    FOREIGN KEY (`Compra_medi_id_compra`)
    REFERENCES `hospital`.`Compra_medi` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operaciones_farmacia1`
    FOREIGN KEY (`farmacia_id_venta`)
    REFERENCES `hospital`.`farmacia` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
